// Generated by scripts/generate_behavior_mappings.py; do not edit.
#include <Rosetta/Battlegrounds/CardSets/GeneratedBehaviorMappings.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/GenerateBloodGemsTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BloodGemRaceBonusTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/GainGoldTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SummonTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/AttackingMinionBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SummonedMinionStatMultiplierTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyTavernSpellHealthBonusTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/GrowingSummonAttackTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/MinionOfferingTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/AddCardTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/FriendlyRaceEnchantmentTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/FreeRefreshTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BuyMinionTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/PersistentRaceBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/CastSpellBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/OnePerTypeRallyBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/HandRaceBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomHandMinionBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomCardToHandTask.hpp>
#include <Rosetta/Common/Enums/TaskEnums.hpp>
#include <Rosetta/Battlegrounds/Models/Minion.hpp>
#include <Rosetta/Battlegrounds/Cards/Cards.hpp>
#include <Rosetta/Battlegrounds/Conditions/SelfCondition.hpp>
#include <Rosetta/Battlegrounds/Enchants/Effects.hpp>
#include <Rosetta/Battlegrounds/Enchants/Enchant.hpp>
#include <vector>
#include <Rosetta/Battlegrounds/Triggers/Trigger.hpp>
#include <utility>
namespace RosettaStone::Battlegrounds {
void GeneratedBehaviorMappings::AddAll(std::map<std::string, CardDef>& cards) {
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(3), Effects::HealthN(3)}}); cards.emplace("BG26_523e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(4), Effects::HealthN(4)}}); cards.emplace("BG31_843e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(3), Effects::HealthN(3)}}); cards.emplace("BG22_HERO_200_Buddy_e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(4), Effects::HealthN(4)}}); cards.emplace("BG32_846e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(2)}}); cards.emplace("BG26_810e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(3), Effects::HealthN(3)}}); cards.emplace("BG33_893e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(1)}}); cards.emplace("BG25_011e2", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(15), Effects::HealthN(15)}}); cards.emplace("BG34_320e", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomCardToHandTask{Race::ELEMENTAL, 0, 1}); cards.emplace("BGS_123", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomCardToHandTask{Race::ELEMENTAL, 0, 2}); cards.emplace("TB_BaconUps_162", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TAKE_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomHandMinionBuffTask{2, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG29_300", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TAKE_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomHandMinionBuffTask{4, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG29_300_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::HERO_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_523e", Race::DEMON}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_523", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::HERO_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_523e", Race::DEMON}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_523e", Race::DEMON}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_523_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::OnePerTypeRallyBuffTask{15, 15, 1}); cards.emplace("BG34_320", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::OnePerTypeRallyBuffTask{15, 15, 2}); cards.emplace("BG34_320_G", CardDef{std::move(p)}); }
  { cards.emplace("BG25_001", CardDef{}); }
  { cards.emplace("BG25_001_G", CardDef{}); }
  { cards.emplace("BG26_175", CardDef{}); }
  { cards.emplace("BG26_175_G", CardDef{}); }
  { cards.emplace("BG32_236", CardDef{}); }
  { cards.emplace("BG32_236_G", CardDef{}); }
  { cards.emplace("TB_BaconUps_099", CardDef{}); }
  { cards.emplace("TB_BaconUps_159", CardDef{}); }
  { cards.emplace("TB_BaconUps_251", CardDef{}); }
  { cards.emplace("BG31_HERO_801pt", CardDef{}); }
  { cards.emplace("BG31_HERO_801pt_G", CardDef{}); }
  { cards.emplace("BGS_115t", CardDef{}); }
  { cards.emplace("BGS_115t_G", CardDef{}); }
  { cards.emplace("BG_BOT_312t", CardDef{}); }
  { cards.emplace("TB_BaconUps_032t", CardDef{}); }
  { cards.emplace("BG_ICC_026t", CardDef{}); }
  { cards.emplace("BG_ICC_026t_G", CardDef{}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{1, false}); cards.emplace("BG23_002", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{2, false}); cards.emplace("BG23_002_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{1, false}); cards.emplace("BG26_135", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{2, false}); cards.emplace("BG26_135_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::FreeRefreshTask{1}); cards.emplace("BGS_116", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::FreeRefreshTask{2}); cards.emplace("TB_BaconUps_167", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{4, 4, 0, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("TB_BaconShop_HERO_01_Buddy_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{0, 0, 1, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG20_HERO_102_Buddy_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{20, 20, 2, true, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_950", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{20, 20, 3, true, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_950_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::BUFF_TARGET, 1, 3, 3}); cards.emplace("BG36_345", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::BUFF_TARGET, 1, 6, 6}); cards.emplace("BG36_345_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::SET_TARGET_STATS, 2, 50, 50}); cards.emplace("BG36_356", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::SET_TARGET_STATS, 2, 100, 100}); cards.emplace("BG36_356_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::GenerateBloodGemsTask{1}); cards.emplace("BG20_101", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::GenerateBloodGemsTask{2}); cards.emplace("BG20_101_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_START}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::GainGoldTask{1}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_147", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_START}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::GainGoldTask{2}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_147_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_200t", 1}); cards.emplace("BG36_200", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_200_Gt", 2}); cards.emplace("BG36_200_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBuffTask{4, 1}); cards.emplace("BG36_207", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBuffTask{8, 2}); cards.emplace("BG36_207_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_202", 1}); cards.emplace("BG36_210", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_202_G", 1}); cards.emplace("BG36_210_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG27_002t", 2}); cards.emplace("BG27_002", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG27_002t", 4}); cards.emplace("BG27_002_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_888", 1}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_888", 1}); cards.emplace("BG32_111", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_888", 2}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_888", 2}); cards.emplace("BG32_111_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"EBG_Spell_014", 1}); cards.emplace("BG32_170", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"EBG_Spell_014", 2}); cards.emplace("BG32_170_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_168", 1}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_168", 1}); cards.emplace("BG32_820", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_168", 2}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_168", 2}); cards.emplace("BG32_820_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t", 3}); cards.emplace("BG30_125", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t", 6}); cards.emplace("BG30_125_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_TTN_401", 1}); cards.emplace("BG32_172", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_TTN_401_G", 1}); cards.emplace("BG32_172_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG19_010", 2}); cards.emplace("BG35_604", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG19_010_G", 2}); cards.emplace("BG35_604_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG19_010t", 1}); cards.emplace("BG19_010", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG19_010_Gt", 1}); cards.emplace("BG19_010_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG25_010t", 1}); cards.emplace("BG25_010", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG25_010_Gt", 2}); cards.emplace("BG25_010_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG25_008", 1}); cards.emplace("BG25_009", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG25_008_G", 1}); cards.emplace("BG25_009_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::ELEMENTAL); }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG32_846e", Race::ELEMENTAL}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_846", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::ELEMENTAL); }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG32_846e", Race::ELEMENTAL}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG32_846e", Race::ELEMENTAL}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_846_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRaceBuffTask{Race::BEAST, 2, 1, Race::BEAST}); cards.emplace("BG36_211", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRaceBuffTask{Race::BEAST, 4, 2, Race::BEAST}); cards.emplace("BG36_211_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::BloodGemRaceBonusTask{Race::ELEMENTAL, 2, 2}); cards.emplace("BG36_351", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::BloodGemRaceBonusTask{Race::ELEMENTAL, 4, 4}); cards.emplace("BG36_351_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::AttackingMinionBuffTask{3, 1, Race::DRAGON}); cards.emplace("BG29_816", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::AttackingMinionBuffTask{6, 2, Race::DRAGON}); cards.emplace("BG29_816_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_810e", Race::PIRATE}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_810", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_810e", Race::PIRATE}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_810e", Race::PIRATE}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_810_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 1, 0}); cards.emplace("BG25_011", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 2, 0}); cards.emplace("BG25_011_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::ELEMENTAL, 2, 0}); cards.emplace("BG32_841", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::ELEMENTAL, 4, 0}); cards.emplace("BG32_841_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::HandRaceBuffTask{6, 6}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_137", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::HandRaceBuffTask{12, 12}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_137_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::NAGA); }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::NAGA, 2, 3, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_622", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::NAGA); }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::NAGA, 4, 6, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_622_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::MURLOC, 3, 3, true, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_704", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::MURLOC, 6, 6, true, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_704_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::INVALID, 8, 8, false, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_703", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::INVALID, 16, 16, false, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_703_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::INVALID, 2, 2, false, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_762", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::CastSpellBuffTask{Race::INVALID, 4, 4, false, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_762_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.GetTier() <= 3; }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG33_893e", Race::MURLOC}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_893", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.GetTier() <= 3; }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG33_893e", Race::MURLOC}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG33_893e", Race::MURLOC}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_893_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyTavernSpellHealthBonusTask{1}); cards.emplace("BG33_924", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyTavernSpellHealthBonusTask{2}); cards.emplace("BG33_924_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::GrowingSummonAttackTask{Race::BEAST, 2, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_602", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::GrowingSummonAttackTask{Race::BEAST, 4, 4}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_602_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.getPlayerCallback().isInCombat && source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::SummonedMinionStatMultiplierTask{Race::BEAST, 2, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_802", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.getPlayerCallback().isInCombat && source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::SummonedMinionStatMultiplierTask{Race::BEAST, 3, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_802_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::MinionOfferingTask{Race::MURLOC, 1, 7, 3, true}); cards.emplace("BGS_020", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t", 2}); cards.emplace("BG28_300", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t_G", 4}); cards.emplace("BG28_300_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_BOT_312t", 1}); cards.emplace("BG29_611", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"TB_BaconUps_032t", 1}); cards.emplace("BG29_611_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG28_603t", 1}); cards.emplace("BG31_803", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG28_603t_G", 2}); cards.emplace("BG31_803_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG34_689", 1}); cards.emplace("BG34_682", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG34_689", 2}); cards.emplace("BG34_682_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG35_149", 1}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG35_149", 1}); cards.emplace("BG35_143", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG35_149", 2}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG35_149", 2}); cards.emplace("BG35_143_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_624", 1}); cards.emplace("BG36_854", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_624", 2}); cards.emplace("BG36_854_G", CardDef{std::move(p)}); }
}
}
