// Generated by scripts/generate_behavior_mappings.py; do not edit.
#include <Rosetta/Battlegrounds/CardSets/GeneratedBehaviorMappings.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/GenerateBloodGemsTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BloodGemRaceBonusTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/GainGoldTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SummonTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyBloodGemGolemTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyBloodGemSelfTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/EndTurnLastTavernSpellTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyBloodGemOtherTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyBloodGemAttackerTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SpellCastAdjacentBloodGemTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SpendGoldThresholdSpellTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SpendGoldThresholdBountyTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BuyTavernSpellMurlocTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/HeroDamageThresholdSpellTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyRemoveKeywordsTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyRandomRaceKeywordTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/CastTavernSpellOnAdjacentTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomBountyToHandTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/ConfigureAttackThresholdTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/ArmFodderRefreshTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyGainTargetAttackTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BattlecryTavernSpellDiscoverTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/EndTurnConsumeHighestTavernTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomGoldenTierMinionToHandTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/AttackingMinionBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SummonedMinionStatMultiplierTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RallyTavernSpellHealthBonusTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BattlecryTavernSpellAttackBonusTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/GrowingSummonAttackTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/MinionOfferingTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/AddCardTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/FriendlyRaceEnchantmentTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/FreeRefreshTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BuyMinionTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/PersistentRaceBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/CastSpellBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/OnePerTypeRallyBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/HandRaceBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomHandMinionBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomFriendlyRaceTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomEnemyDamageTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomCardToHandTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/LeapfroggerDeathrattleTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/MaxHealthDeathrattleTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/RandomSummonFromPoolTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/PersistentBeetleBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BattlecryTavernSpellDiscountTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/EndTurnTavernSpellStatsTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/BattlecrySpentGoldRaceHealthTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/PersistentTavernTierBuffTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/ArmRefreshRandomShopStatsTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SpellCastSelfScalingTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/SpellCastOnSelfHealthTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/StartCombatHandStatsTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/StartCombatHighestHandMurlocSummonTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/StartCombatDestroyAdjacentTask.hpp>
#include <Rosetta/Battlegrounds/Tasks/SimpleTasks/StartCombatHandSelfCopyTask.hpp>
#include <Rosetta/Common/Enums/TaskEnums.hpp>
#include <Rosetta/Battlegrounds/Models/Minion.hpp>
#include <Rosetta/Battlegrounds/Models/Player.hpp>
#include <Rosetta/Battlegrounds/Cards/Cards.hpp>
#include <Rosetta/Battlegrounds/Conditions/SelfCondition.hpp>
#include <Rosetta/Battlegrounds/Enchants/Effects.hpp>
#include <Rosetta/Battlegrounds/Enchants/Enchant.hpp>
#include <vector>
#include <Rosetta/Battlegrounds/Triggers/Trigger.hpp>
#include <utility>
namespace RosettaStone::Battlegrounds {
void GeneratedBehaviorMappings::AddAll(std::map<std::string, CardDef>& cards) {
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(3), Effects::HealthN(3)}}); cards.emplace("BG26_523e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(4), Effects::HealthN(4)}}); cards.emplace("BG31_843e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(3), Effects::HealthN(3)}}); cards.emplace("BG22_HERO_200_Buddy_e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(4), Effects::HealthN(4)}}); cards.emplace("BG32_846e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(2)}}); cards.emplace("BG26_810e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(3), Effects::HealthN(3)}}); cards.emplace("BG33_893e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(1)}}); cards.emplace("BG25_011e2", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(15), Effects::HealthN(15)}}); cards.emplace("BG34_320e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(1), Effects::HealthN(1)}}); cards.emplace("BG26_963e", CardDef{std::move(p)}); }
  { Power p; p.AddEnchant(Enchant{std::vector<Effect>{Effects::AttackN(4), Effects::HealthN(4)}}); cards.emplace("BG21_014e", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::MaxHealthDeathrattleTask{1}); cards.emplace("BG21_006", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::MaxHealthDeathrattleTask{2}); cards.emplace("BG21_006_G", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatDestroyAdjacentTask{false}); cards.emplace("BG31_999", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatDestroyAdjacentTask{true}); cards.emplace("BG31_999_G", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatHandSelfCopyTask{false}); cards.emplace("BG32_330", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatHandSelfCopyTask{true}); cards.emplace("BG32_330_G", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatHighestHandMurlocSummonTask{1}); cards.emplace("BG27_556", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatHighestHandMurlocSummonTask{2}); cards.emplace("BG27_556_G", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatHandStatsTask{1}); cards.emplace("BG26_354", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::StartCombatHandStatsTask{2}); cards.emplace("BG26_354_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomSummonFromPoolTask{Race::BEAST, 1, 7, 6, false}); cards.emplace("BG25_806", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomSummonFromPoolTask{Race::BEAST, 1, 7, 12, true}); cards.emplace("BG25_806_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomCardToHandTask{Race::MECHANICAL, 0, 1, true}); cards.emplace("BG26_148", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomCardToHandTask{Race::MECHANICAL, 0, 2, true}); cards.emplace("BG26_148_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomCardToHandTask{Race::INVALID, 6, 1, false}); p.AddDeathrattleTask(SimpleTasks::RandomCardToHandTask{Race::INVALID, 6, 1, false}); p.AddRallyTask(SimpleTasks::RandomCardToHandTask{Race::INVALID, 6, 1, false}); cards.emplace("BG34_319", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomCardToHandTask{Race::INVALID, 6, 2, false}); p.AddDeathrattleTask(SimpleTasks::RandomCardToHandTask{Race::INVALID, 6, 2, false}); p.AddRallyTask(SimpleTasks::RandomCardToHandTask{Race::INVALID, 6, 2, false}); cards.emplace("BG34_319_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::LeapfroggerDeathrattleTask{1, 1}); cards.emplace("BG34_Giant_031", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::LeapfroggerDeathrattleTask{2, 2}); cards.emplace("BG34_Giant_031_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomCardToHandTask{Race::ELEMENTAL, 0, 1, false}); cards.emplace("BGS_123", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomCardToHandTask{Race::ELEMENTAL, 0, 2, false}); cards.emplace("TB_BaconUps_162", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TAKE_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomHandMinionBuffTask{2, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG29_300", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TAKE_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomHandMinionBuffTask{4, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG29_300_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::HERO_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_523e", Race::DEMON}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_523", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::HERO_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_523e", Race::DEMON}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_523e", Race::DEMON}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_523_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::OnePerTypeRallyBuffTask{15, 15, 1}); cards.emplace("BG34_320", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::OnePerTypeRallyBuffTask{15, 15, 2}); cards.emplace("BG34_320_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{1, false}); cards.emplace("BG23_002", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{2, false}); cards.emplace("BG23_002_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{1, false}); cards.emplace("BG26_135", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GainGoldTask{2, false}); cards.emplace("BG26_135_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::FreeRefreshTask{1}); cards.emplace("BGS_116", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::FreeRefreshTask{2}); cards.emplace("TB_BaconUps_167", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{4, 4, 0, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("TB_BaconShop_HERO_01_Buddy_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{0, 0, 1, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG20_HERO_102_Buddy_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{20, 20, 2, true, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_950", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::BUY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetTasks({SimpleTasks::BuyMinionTask{20, 20, 3, true, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_950_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::BUFF_TARGET, 1, 3, 3}); cards.emplace("BG36_345", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::BUFF_TARGET, 1, 6, 6}); cards.emplace("BG36_345_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::SET_TARGET_STATS, 2, 50, 50}); cards.emplace("BG36_356", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::SET_TARGET_STATS, 2, 100, 100}); cards.emplace("BG36_356_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::GenerateBloodGemsTask{1}); cards.emplace("BG20_101", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::GenerateBloodGemsTask{2}); cards.emplace("BG20_101_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_START}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::GainGoldTask{1}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_147", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_START}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::GainGoldTask{2}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_147_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_200t", 1}); cards.emplace("BG36_200", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_200_Gt", 2}); cards.emplace("BG36_200_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBuffTask{4, 1}); cards.emplace("BG36_207", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBuffTask{8, 2}); cards.emplace("BG36_207_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_202", 1}); cards.emplace("BG36_210", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::SummonTask{"BG36_202_G", 1}); cards.emplace("BG36_210_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG27_002t", 2}); cards.emplace("BG27_002", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG27_002t", 4}); cards.emplace("BG27_002_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_888", 1}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_888", 1}); cards.emplace("BG32_111", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_888", 2}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_888", 2}); cards.emplace("BG32_111_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"EBG_Spell_014", 1}); cards.emplace("BG32_170", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"EBG_Spell_014", 2}); cards.emplace("BG32_170_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_168", 1}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_168", 1}); cards.emplace("BG32_820", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG28_168", 2}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_168", 2}); cards.emplace("BG32_820_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t", 3}); cards.emplace("BG30_125", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t", 6}); cards.emplace("BG30_125_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_TTN_401", 1}); cards.emplace("BG32_172", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_TTN_401_G", 1}); cards.emplace("BG32_172_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG19_010", 2}); cards.emplace("BG35_604", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG19_010_G", 2}); cards.emplace("BG35_604_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::ELEMENTAL); }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG32_846e", Race::ELEMENTAL}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_846", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::ELEMENTAL); }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG32_846e", Race::ELEMENTAL}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG32_846e", Race::ELEMENTAL}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_846_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRaceBuffTask{Race::BEAST, 2, 1, Race::BEAST}); cards.emplace("BG36_211", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRaceBuffTask{Race::BEAST, 4, 2, Race::BEAST}); cards.emplace("BG36_211_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::BloodGemRaceBonusTask{Race::ELEMENTAL, 2, 2}); cards.emplace("BG36_351", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::BloodGemRaceBonusTask{Race::ELEMENTAL, 4, 4}); cards.emplace("BG36_351_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemGolemTask{1}); cards.emplace("BG36_333", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemGolemTask{2}); cards.emplace("BG36_333_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::DISCOVER_TAVERN_SPELL, 2, 0, 0, 1}); cards.emplace("BG36_342", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::DISCOVER_TAVERN_SPELL, 2, 0, 0, 2}); cards.emplace("BG36_342_G", CardDef{std::move(p)}); }
  { cards.emplace("BG36_344", CardDef{}); }
  { cards.emplace("BG36_344_G", CardDef{}); }
  { cards.emplace("BG36_332", CardDef{}); }
  { cards.emplace("BG36_332_G", CardDef{}); }
  { Power p; p.AddRallyTask(SimpleTasks::AttackingMinionBuffTask{3, 1, Race::DRAGON}); cards.emplace("BG29_816", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::AttackingMinionBuffTask{6, 2, Race::DRAGON}); cards.emplace("BG29_816_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_810e", Race::PIRATE}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_810", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_810e", Race::PIRATE}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_810e", Race::PIRATE}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_810_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 1, 0, false, -1}); cards.emplace("BG25_011", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 2, 0, false, -1}); cards.emplace("BG25_011_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::ELEMENTAL, 2, 0, false, -1}); cards.emplace("BG32_841", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::ELEMENTAL, 4, 0, false, -1}); cards.emplace("BG32_841_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::HandRaceBuffTask{6, 6}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_137", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::HandRaceBuffTask{12, 12}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_137_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::NAGA); }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::NAGA, 2, 3, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_RACE}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_622", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::NAGA); }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::NAGA, 4, 6, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_RACE}, SimpleTasks::ApplyMinionStatBuffTask{Race::NAGA, 4, 6, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_RACE}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_622_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::MURLOC, 3, 3, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_AND_HAND_RACE}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_704", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::MURLOC); }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::MURLOC, 6, 6, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_AND_HAND_RACE}, SimpleTasks::ApplyMinionStatBuffTask{Race::MURLOC, 6, 6, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_AND_HAND_RACE}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_704_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 8, 8, SimpleTasks::MinionBuffTarget::LEFTMOST_HAND}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_703", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 16, 16, SimpleTasks::MinionBuffTarget::LEFTMOST_HAND}, SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 16, 16, SimpleTasks::MinionBuffTarget::LEFTMOST_HAND}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_703_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 2, 2, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_762", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 4, 4, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}, SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 4, 4, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_762_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.GetTier() <= 3; }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG33_893e", Race::MURLOC}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_893", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_PLAY_MINION}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.GetTier() <= 3; }}); t.SetTasks({SimpleTasks::FriendlyRaceEnchantmentTask{"BG33_893e", Race::MURLOC}, SimpleTasks::FriendlyRaceEnchantmentTask{"BG33_893e", Race::MURLOC}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_893_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyTavernSpellHealthBonusTask{1}); cards.emplace("BG33_924", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyTavernSpellHealthBonusTask{2}); cards.emplace("BG33_924_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::GrowingSummonAttackTask{Race::BEAST, 2, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_602", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::GrowingSummonAttackTask{Race::BEAST, 4, 4}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_602_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.getPlayerCallback().isInCombat && source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::SummonedMinionStatMultiplierTask{Race::BEAST, 2, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_802", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SUMMON}; t.SetTriggerSource(TriggerSource::MINIONS_EXCEPT_SELF); t.SetCondition(SelfCondition{[](Minion& source) { return source.getPlayerCallback().isInCombat && source.HasRace(Race::BEAST); }}); t.SetTasks({SimpleTasks::SummonedMinionStatMultiplierTask{Race::BEAST, 3, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG26_802_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::MinionOfferingTask{Race::MURLOC, 1, 7, 3, true}); cards.emplace("BGS_020", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::ELEMENTAL, 8, 8, SimpleTasks::MinionBuffTarget::TAVERN_RACE_PERSISTENT}); p.AddDeathrattleTask(SimpleTasks::ApplyMinionStatBuffTask{Race::ELEMENTAL, 8, 8, SimpleTasks::MinionBuffTarget::TAVERN_RACE_PERSISTENT}); cards.emplace("BG26_162", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::ELEMENTAL, 16, 16, SimpleTasks::MinionBuffTarget::TAVERN_RACE_PERSISTENT}); p.AddDeathrattleTask(SimpleTasks::ApplyMinionStatBuffTask{Race::ELEMENTAL, 16, 16, SimpleTasks::MinionBuffTarget::TAVERN_RACE_PERSISTENT}); cards.emplace("BG26_162_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 8, 8, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); p.AddDeathrattleTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 8, 8, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); cards.emplace("BG27_016", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 16, 16, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); p.AddDeathrattleTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 16, 16, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); cards.emplace("BG27_016_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecryTavernSpellAttackBonusTask{1}); cards.emplace("BG33_830", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecryTavernSpellAttackBonusTask{2}); cards.emplace("BG33_830_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GenerateBloodGemsTask{2}); cards.emplace("BG20_100", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::GenerateBloodGemsTask{4}); cards.emplace("BG20_100_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG34_689", 1}); cards.emplace("BG34_683", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG34_689", 2}); cards.emplace("BG34_683_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t", 2}); cards.emplace("BG28_300", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_ICC_026t_G", 4}); cards.emplace("BG28_300_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG_BOT_312t", 1}); cards.emplace("BG29_611", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"TB_BaconUps_032t", 1}); cards.emplace("BG29_611_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG28_603t", 1}); cards.emplace("BG31_803", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::SummonTask{"BG28_603t_G", 2}); cards.emplace("BG31_803_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG34_689", 1}); cards.emplace("BG34_682", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG34_689", 2}); cards.emplace("BG34_682_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG35_149", 1}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG35_149", 1}); cards.emplace("BG35_143", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG35_149", 2}); p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG35_149", 2}); cards.emplace("BG35_143_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_624", 1}); cards.emplace("BG36_854", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_624", 2}); cards.emplace("BG36_854_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_963e", Race::DRAGON, true}); p.AddStartCombatTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_963e", Race::DRAGON, true}); cards.emplace("BG26_963", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_963e", Race::DRAGON, true}); p.AddStartCombatTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_963e", Race::DRAGON, true}); p.AddBattlecryTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_963e", Race::DRAGON, true}); p.AddStartCombatTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG26_963e", Race::DRAGON, true}); cards.emplace("BG26_963_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 1, 0, false, -1}); cards.emplace("BG33_323", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 2, 0, false, -1}); cards.emplace("BG33_323_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentRaceBuffTask{Race::ELEMENTAL, 0, 2, false, -1}); cards.emplace("BG32_842", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentRaceBuffTask{Race::ELEMENTAL, 0, 4, false, -1}); cards.emplace("BG32_842_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 2, 0, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); cards.emplace("BG29_873", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 4, 0, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); cards.emplace("BG29_873_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 2, 1, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); cards.emplace("BG25_041", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 4, 2, SimpleTasks::MinionBuffTarget::TAVERN_ALL_PERSISTENT}); cards.emplace("BG25_041_G", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG21_014e", Race::DRAGON}); cards.emplace("BG21_014", CardDef{std::move(p)}); }
  { Power p; p.AddStartCombatTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG21_014e", Race::DRAGON}); p.AddStartCombatTask(SimpleTasks::FriendlyRaceEnchantmentTask{"BG21_014e", Race::DRAGON}); cards.emplace("BG21_014_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 1, 0, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_RACE}}); p.AddTrigger(std::move(t)); cards.emplace("BG27_005", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 1, 0, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_RACE}, SimpleTasks::ApplyMinionStatBuffTask{Race::INVALID, 1, 0, SimpleTasks::MinionBuffTarget::FRIENDLY_BOARD_RACE}}); p.AddTrigger(std::move(t)); cards.emplace("BG27_005_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::ELEMENTAL, 3, 2, SimpleTasks::MinionBuffTarget::TAVERN_RACE_PERSISTENT}}); p.AddTrigger(std::move(t)); cards.emplace("BG28_707", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetCondition(SelfCondition{[](Minion&) { return true; }}); t.SetTasks({SimpleTasks::ApplyMinionStatBuffTask{Race::ELEMENTAL, 3, 2, SimpleTasks::MinionBuffTarget::TAVERN_RACE_PERSISTENT}, SimpleTasks::ApplyMinionStatBuffTask{Race::ELEMENTAL, 3, 2, SimpleTasks::MinionBuffTarget::TAVERN_RACE_PERSISTENT}}); p.AddTrigger(std::move(t)); cards.emplace("BG28_707_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::BloodGemRaceBonusTask{Race::QUILBOAR, 1, 1}); cards.emplace("BG33_885", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::BloodGemRaceBonusTask{Race::QUILBOAR, 2, 2}); cards.emplace("BG33_885_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BloodGemRaceBonusTask{Race::QUILBOAR, 1, 1}); p.AddDeathrattleTask(SimpleTasks::BloodGemRaceBonusTask{Race::QUILBOAR, 1, 1}); cards.emplace("BG23_017", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BloodGemRaceBonusTask{Race::QUILBOAR, 2, 2}); p.AddDeathrattleTask(SimpleTasks::BloodGemRaceBonusTask{Race::QUILBOAR, 2, 2}); cards.emplace("BG23_017_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::OnePerTypeRallyBuffTask{3, 3, 1}); cards.emplace("BG27_080", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::OnePerTypeRallyBuffTask{6, 6, 2}); cards.emplace("BG27_080_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::BattlecryTavernSpellAttackBonusTask{1}); cards.emplace("BG32_880", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::BattlecryTavernSpellAttackBonusTask{2}); cards.emplace("BG32_880_G", CardDef{std::move(p)}); }
  { Power p; { Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 2, 0, false, -1}}); p.AddTrigger(std::move(t)); } cards.emplace("BG34_692", CardDef{std::move(p)}); }
  { Power p; { Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 4, 0, false, -1}}); p.AddTrigger(std::move(t)); } cards.emplace("BG34_692_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::MURLOC, 3, 0, true, -1}); cards.emplace("BG35_140", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::MURLOC, 6, 0, true, -1}); cards.emplace("BG35_140_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::MURLOC, 0, 3, true, -1}); cards.emplace("BG35_141", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentRaceBuffTask{Race::MURLOC, 0, 6, true, -1}); cards.emplace("BG35_141_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 2, 0, false, 4}); cards.emplace("BG34_690", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentRaceBuffTask{Race::UNDEAD, 4, 0, false, 8}); cards.emplace("BG34_690_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomFriendlyRaceTask{Race::ALL, 0, 0, 1, true, false}); cards.emplace("BG_OG_221", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomFriendlyRaceTask{Race::ALL, 0, 0, 2, true, false}); cards.emplace("TB_BaconUps_014", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomEnemyDamageTask{4, 1}); cards.emplace("BG_BOT_606", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomEnemyDamageTask{4, 2}); cards.emplace("TB_BaconUps_028", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_520t", 1}); cards.emplace("BG36_521", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_520t", 2}); cards.emplace("BG36_521_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_880", 1}); cards.emplace("BG36_731", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG36_880", 2}); cards.emplace("BG36_731_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_518", 1}); cards.emplace("BG36_760", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::AddCardTask{"BG28_518", 2}); cards.emplace("BG36_760_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentRaceBuffTask{Race::NAGA, 2, 1, false, -1}); cards.emplace("BG31_925", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentRaceBuffTask{Race::NAGA, 4, 2, false, -1}); cards.emplace("BG31_925_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentBeetleBuffTask{2, 1}); p.AddDeathrattleTask(SimpleTasks::PersistentBeetleBuffTask{2, 1}); cards.emplace("BG31_801", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentBeetleBuffTask{4, 2}); p.AddDeathrattleTask(SimpleTasks::PersistentBeetleBuffTask{4, 2}); cards.emplace("BG31_801_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentBeetleBuffTask{5, 5}); cards.emplace("BG31_809", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::PersistentBeetleBuffTask{10, 10}); cards.emplace("BG31_809_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecryTavernSpellDiscountTask{1}); cards.emplace("BG31_330", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecryTavernSpellDiscountTask{2}); cards.emplace("BG31_330_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnTavernSpellStatsTask{1, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_821", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnTavernSpellStatsTask{2, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_821_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::AddCardTask{"BG31_893", 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG31_326", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::AddCardTask{"BG31_893", 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG31_326_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG36_520t", 1}); cards.emplace("BG36_520", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::AddCardTask{"BG36_520t", 2}); cards.emplace("BG36_520_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::AddCardTask{"BG28_698", 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_684", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::AddCardTask{"BG28_698", 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_684_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecrySpentGoldRaceHealthTask{1}); cards.emplace("BG26_814", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecrySpentGoldRaceHealthTask{2}); cards.emplace("BG26_814_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentTavernTierBuffTask{3, 3, 3}); cards.emplace("BG35_152", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::PersistentTavernTierBuffTask{6, 6, 3}); cards.emplace("BG35_152_G", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::ArmRefreshRandomShopStatsTask{4, 4}); cards.emplace("BG34_856", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::ArmRefreshRandomShopStatsTask{8, 8}); cards.emplace("BG34_856_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ArmRefreshRandomShopStatsTask{10, 10}); cards.emplace("BG34_865", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ArmRefreshRandomShopStatsTask{20, 20}); cards.emplace("BG34_865_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpellCastSelfScalingTask{2, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_921", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpellCastSelfScalingTask{4, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_921_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpellCastOnSelfHealthTask{1}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_921", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpellCastOnSelfHealthTask{2}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_921_G", CardDef{std::move(p)}); }
  { cards.emplace("BG32_341", CardDef{}); }
  { cards.emplace("BG32_341_G", CardDef{}); }
  { cards.emplace("BG35_341", CardDef{}); }
  { cards.emplace("BG35_341_G", CardDef{}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomTavernSpellToHandTask{2, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG28_595", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomTavernSpellToHandTask{4, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG28_595_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomTavernSpellToHandTask{2, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_764", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomTavernSpellToHandTask{4, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_764_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnStatTransferTask{1, 0, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_235", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnStatTransferTask{2, 0, false, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG32_235_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnStatTransferTask{1, 1, true, 0}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_145", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnStatTransferTask{2, 2, true, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_145_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyHighestHandSummonTask{1}); cards.emplace("BG34_140", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyHighestHandSummonTask{2}); cards.emplace("BG34_140_G", CardDef{std::move(p)}); }
  { cards.emplace("BG34_142", CardDef{}); }
  { cards.emplace("BG34_142_G", CardDef{}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyHighestHandMurlocBuffTask{1}); cards.emplace("BG34_143", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyHighestHandMurlocBuffTask{2}); cards.emplace("BG34_143_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemSelfTask{3}); cards.emplace("BG33_883", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemSelfTask{6}); cards.emplace("BG33_883_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemSelfTask{1}); cards.emplace("BG33_886", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemSelfTask{2}); cards.emplace("BG33_886_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SELL_MINION}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomCardToHandTask{Race::INVALID, 1, 1, false}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_140", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SELL_MINION}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomCardToHandTask{Race::INVALID, 1, 2, false}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_140_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnLastTavernSpellTask{1}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_123", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnLastTavernSpellTask{2}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_123_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemOtherTask{1}); cards.emplace("BG20_104", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemOtherTask{2}); cards.emplace("BG20_104_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecryTavernSpellDiscoverTask{1}); cards.emplace("BG28_550", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::BattlecryTavernSpellDiscoverTask{2}); cards.emplace("BG28_550_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnConsumeHighestTavernTask{1}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_500", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::EndTurnConsumeHighestTavernTask{2}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_500_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomGoldenTierMinionToHandTask{1}); cards.emplace("BG36_343", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomGoldenTierMinionToHandTask{2}); cards.emplace("BG36_343_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyGainTargetAttackTask{1}); cards.emplace("BG34_604", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyGainTargetAttackTask{2}); cards.emplace("BG34_604_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRemoveKeywordsTask{3}); cards.emplace("BG25_016", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRemoveKeywordsTask{3}); cards.emplace("BG25_016_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRandomRaceKeywordTask{Race::MURLOC, GameTag::VENOMOUS, 1}); cards.emplace("BG33_318", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyRandomRaceKeywordTask{Race::MURLOC, GameTag::VENOMOUS, 2}); cards.emplace("BG33_318_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ArmFodderRefreshTask{3, 1}); cards.emplace("BG35_150", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ArmFodderRefreshTask{3, 2}); cards.emplace("BG35_150_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SELL_MINION}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::ArmFodderRefreshTask{1, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_155", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SELL_MINION}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::ArmFodderRefreshTask{1, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_155_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomBountyToHandTask{1}); p.AddDeathrattleTask(SimpleTasks::RandomBountyToHandTask{1}); cards.emplace("BG33_821", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::RandomBountyToHandTask{2}); p.AddDeathrattleTask(SimpleTasks::RandomBountyToHandTask{2}); cards.emplace("BG33_821_G", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ConfigureAttackThresholdTask{6}); cards.emplace("BG35_814", CardDef{std::move(p)}); }
  { Power p; p.AddBattlecryTask(SimpleTasks::ConfigureAttackThresholdTask{6}); cards.emplace("BG35_814_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RandomBountyToHandTask{1}); cards.emplace("BG33_822", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RandomBountyToHandTask{2}); cards.emplace("BG33_822_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemAttackerTask{1}); cards.emplace("BG33_430", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::RallyBloodGemAttackerTask{2}); cards.emplace("BG33_430_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpellCastAdjacentBloodGemTask{1}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_510", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::AFTER_CAST_SPELL}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpellCastAdjacentBloodGemTask{2}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_510_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::TRIGGER_BATTLECRY, 1, 0, 0, 1}); cards.emplace("BG36_701", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::TRIGGER_BATTLECRY, 1, 0, 0, 2}); cards.emplace("BG36_701_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::TAKE_HIGHEST_TAVERN, 2, 0, 0, 1}); cards.emplace("BG36_354", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::TAKE_HIGHEST_TAVERN, 2, 0, 0, 2}); cards.emplace("BG36_354_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::DEVOUR_TAVERN_DEMONS, 2, 0, 0, 1}); cards.emplace("BG36_503", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::DEVOUR_TAVERN_DEMONS, 2, 0, 0, 2}); cards.emplace("BG36_503_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpendGoldThresholdSpellTask{7, "BG34_444", 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_858", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpendGoldThresholdSpellTask{7, "BG34_444", 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG34_858_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::HERO_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::HeroDamageThresholdSpellTask{3, "BG28_168", 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_733", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::HERO_DAMAGE}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::HeroDamageThresholdSpellTask{3, "BG28_168", 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG36_733_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::DESTROY_UNDEAD_BUFF_SELF, 1, 4, 4, 1}); cards.emplace("BG36_511", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::DESTROY_UNDEAD_BUFF_SELF, 1, 8, 8, 1}); cards.emplace("BG36_511_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::ACTIVATE_FISHBAIT, 2, 5, 0, 1, false, "BG36_205"}); cards.emplace("BG36_201", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::ACTIVATE_FISHBAIT, 2, 10, 0, 1, false, "BG36_205_G"}); cards.emplace("BG36_201_G", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::ACTIVATE_RANDOM_TAVERN_SPELLS, 1, 0, 0, 2}); cards.emplace("BG36_508", CardDef{std::move(p)}); }
  { Power p; p.AddActivate({ActivateEffect::ACTIVATE_RANDOM_TAVERN_SPELLS, 1, 0, 0, 4}); cards.emplace("BG36_508_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::AddCardTask{"BG35_140", 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_142", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::TURN_END}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::AddCardTask{"BG35_140_G", 1}, SimpleTasks::AddCardTask{"BG35_141_G", 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG35_142_G", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::DEAL_DAMAGE}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::DEMON); }}); t.SetTasks({SimpleTasks::DealDamageSelfBuffTask{1, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_155", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::DEAL_DAMAGE}; t.SetTriggerSource(TriggerSource::FRIENDLY); t.SetCondition(SelfCondition{[](Minion& source) { return source.HasRace(Race::DEMON); }}); t.SetTasks({SimpleTasks::DealDamageSelfBuffTask{2, 4}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_155_G", CardDef{std::move(p)}); }
  { cards.emplace("BG35_342", CardDef{}); }
  { cards.emplace("BG35_342_G", CardDef{}); }
  { cards.emplace("BG33_319", CardDef{}); }
  { cards.emplace("BG33_319_G", CardDef{}); }
  { cards.emplace("BG33_825", CardDef{}); }
  { cards.emplace("BG33_825_G", CardDef{}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomFriendlyRaceTask{Race::BEAST, 1, 1, 1, false, true}); cards.emplace("BG36_202", CardDef{std::move(p)}); }
  { Power p; p.AddDeathrattleTask(SimpleTasks::RandomFriendlyRaceTask{Race::BEAST, 2, 2, 1, false, true}); cards.emplace("BG36_202_G", CardDef{std::move(p)}); }
  { cards.emplace("BG36_206", CardDef{}); }
  { cards.emplace("BG36_206_G", CardDef{}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD_EXACT}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpendGoldThresholdBountyTask{9, 1}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_823", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD_EXACT}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::SpendGoldThresholdBountyTask{9, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG33_823_G", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::CastTavernSpellOnAdjacentTask{"BG28_518", 1}); cards.emplace("BG34_925", CardDef{std::move(p)}); }
  { Power p; p.AddRallyTask(SimpleTasks::CastTavernSpellOnAdjacentTask{"BG28_518", 2}); cards.emplace("BG34_925_G", CardDef{std::move(p)}); }
  { cards.emplace("BG35_883", CardDef{}); }
  { cards.emplace("BG35_883_G", CardDef{}); }
  { cards.emplace("BG36_763", CardDef{}); }
  { cards.emplace("BG36_763_G", CardDef{}); }
  { cards.emplace("BG23_HERO_304p", CardDef{}); }
  { cards.emplace("BG23_HERO_305p", CardDef{}); }
  { cards.emplace("BG30_HERO_304p", CardDef{}); }
  { cards.emplace("BG31_HERO_801p", CardDef{}); }
  { cards.emplace("BG31_HERO_802p", CardDef{}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomFriendlyRaceTask{Race::PIRATE, 4, 5, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG31_824", CardDef{std::move(p)}); }
  { Power p; Trigger t{TriggerType::SPEND_GOLD}; t.SetTriggerSource(TriggerSource::SELF); t.SetTasks({SimpleTasks::RandomFriendlyRaceTask{Race::PIRATE, 8, 10, 2}}); p.AddTrigger(std::move(t)); cards.emplace("BG31_824_G", CardDef{std::move(p)}); }
}
}
