// Generated by scripts/generate_behavior_mappings.py; do not edit.
#pragma once
#include <Rosetta/Battlegrounds/Cards/CardDef.hpp>
#include <map>
#include <string>
#include <string_view>
namespace RosettaStone::Battlegrounds {
struct DeclarativeBehaviorRow { std::string_view id, trigger, selector, condition, effect; int amount, goldenScale; };
inline constexpr unsigned DeclarativeBehaviorSchema = 1;
inline constexpr DeclarativeBehaviorRow DeclarativeBehaviorRows[] = {
  {"BG20_101","rally","self","always","generate_blood_gems",1,1},
  {"BG20_101_G","rally","self","always","generate_blood_gems",2,2},
  {"BG26_147","turn_start","self","always","gain_gold",1,1},
  {"BG26_147_G","turn_start","self","always","gain_gold",2,2},
  {"BG36_200","rally","self","always","summon",1,1},
  {"BG36_200_G","rally","self","always","summon",2,2},
  {"BG36_207","rally","other_friendly_minions","always","enchant_stats",1,1},
  {"BG36_207_G","rally","other_friendly_minions","always","enchant_stats",2,2},
  {"BG36_210","rally","self","always","summon",1,1},
  {"BG36_210_G","rally","self","always","summon",1,1},
  {"BG27_002","battlecry","self","always","add_card",2,1},
  {"BG27_002_G","battlecry","self","always","add_card",4,2},
};
class GeneratedBehaviorMappings { public: static void AddAll(std::map<std::string, CardDef>&); };
}
