#include "doctest_proxy.hpp"
#include <Rosetta/Battlegrounds/CardSets/BuddyBehaviors.hpp>
#include <Rosetta/Battlegrounds/CardSets/DetectiveForHireBehaviors.hpp>
#include <Rosetta/Battlegrounds/CardSets/HelpfulCardBehaviors.hpp>
using namespace RosettaStone::Battlegrounds;
TEST_CASE("[Buddy] - Malorne pinned hero-linked behavior") {
 constexpr std::array ids = {"BG32_HERO_001_Buddy", "BG32_HERO_001_Buddy_G", "BG23_HERO_201_Buddy", "BG23_HERO_201_Buddy_G", "BG21_HERO_020_Buddy", "BG21_HERO_020_Buddy_G", "BG21_HERO_000_Buddy", "BG21_HERO_000_Buddy_G", "BG31_HERO_802_Buddy", "BG31_HERO_802_Buddy_G"};
 CHECK(BUDDY_BEHAVIORS.size() == 10);
 CHECK(BUDDY_BEHAVIORS[0].heroID == "BG32_HERO_001");
 CHECK(BUDDY_BEHAVIORS[1].attackPerThreshold == 2);
 CHECK(BUDDY_BEHAVIORS[2].heroID == "BG23_HERO_201");
 CHECK(BUDDY_BEHAVIORS[3].attackPerThreshold == 3);
 CHECK(BUDDY_BEHAVIORS[4].heroID == "BG21_HERO_020");
 CHECK(BUDDY_BEHAVIORS[5].attackPerThreshold == 2);
}

TEST_CASE("[Buddy] - Detective for Hire pinned source/result contract") {
 CHECK(DETECTIVE_FOR_HIRE_BEHAVIORS.size() == 4);
 CHECK(DETECTIVE_FOR_HIRE_BEHAVIORS[0].dbfID == 90403);
 CHECK(DETECTIVE_FOR_HIRE_BEHAVIORS[1].dbfID == 92974);
}

TEST_CASE("[Buddy] - Zippers helpful-card pool remains fail-closed") {
 CHECK(HELPFUL_CARD_BEHAVIORS.empty());
}

TEST_CASE("[Buddy] - Icesnarl combat-kill health behavior is normal/golden") {
 CHECK(BUDDY_COMBAT_KILL_BEHAVIORS.size() == 2);
 CHECK(BUDDY_COMBAT_KILL_BEHAVIORS[0].id == "BG20_HERO_100_Buddy");
 CHECK(BUDDY_COMBAT_KILL_BEHAVIORS[0].healthPerKill == 1);
 CHECK(BUDDY_COMBAT_KILL_BEHAVIORS[1].id == "BG20_HERO_100_Buddy_G");
 CHECK(BUDDY_COMBAT_KILL_BEHAVIORS[1].healthPerKill == 2);
}

TEST_CASE("[Buddy] - Baby Elekk lower-attack play behavior is normal/golden") {
 CHECK(BUDDY_EQUAL_STATS_PLAY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_EQUAL_STATS_PLAY_BEHAVIORS[0].id == "BG20_HERO_101_Buddy");
 CHECK(BUDDY_EQUAL_STATS_PLAY_BEHAVIORS[1].id == "BG20_HERO_101_Buddy_G");
 CHECK(BUDDY_EQUAL_STATS_PLAY_BEHAVIORS[0].attackHealth == 1);
 CHECK(BUDDY_EQUAL_STATS_PLAY_BEHAVIORS[1].attackHealth == 2);
}

TEST_CASE("[Buddy] - Death's Head Sage Blood Gem behavior is normal/golden") {
 CHECK(BUDDY_BLOOD_GEM_BEHAVIORS.size() == 2);
 CHECK(BUDDY_BLOOD_GEM_BEHAVIORS[0].id == "BG20_HERO_103_Buddy");
 CHECK(BUDDY_BLOOD_GEM_BEHAVIORS[1].id == "BG20_HERO_103_Buddy_G");
 CHECK(BUDDY_BLOOD_GEM_BEHAVIORS[0].extraPerGem == 1);
 CHECK(BUDDY_BLOOD_GEM_BEHAVIORS[1].extraPerGem == 2);
}

TEST_CASE("[Buddy] - Dranosh Saurfang For the Horde health behavior") {
 CHECK(BUDDY_HORDE_BEHAVIORS.size() == 2);
 CHECK(BUDDY_HORDE_BEHAVIORS[0].id == "BG20_HERO_102_Buddy");
 CHECK(BUDDY_HORDE_BEHAVIORS[1].id == "BG20_HERO_102_Buddy_G");
 CHECK(BUDDY_HORDE_BEHAVIORS[0].healthMultiplier == 1);
 CHECK(BUDDY_HORDE_BEHAVIORS[1].healthMultiplier == 2);
}

TEST_CASE("[Buddy] - Master Gadrin adjacent attack copy behavior") {
 CHECK(BUDDY_ADJACENT_ATTACK_BEHAVIORS.size() == 2);
 CHECK(BUDDY_ADJACENT_ATTACK_BEHAVIORS[0].id == "BG20_HERO_201_Buddy");
 CHECK(!BUDDY_ADJACENT_ATTACK_BEHAVIORS[0].bothAdjacent);
 CHECK(BUDDY_ADJACENT_ATTACK_BEHAVIORS[1].id == "BG20_HERO_201_Buddy_G");
 CHECK(BUDDY_ADJACENT_ATTACK_BEHAVIORS[1].bothAdjacent);
}

TEST_CASE("[Buddy] - Flight Trainer flightpath progress is normal/golden") {
 CHECK(BUDDY_FLIGHTPATH_BEHAVIORS.size() == 2);
 CHECK(BUDDY_FLIGHTPATH_BEHAVIORS[0].id == "BG20_HERO_283_Buddy");
 CHECK(BUDDY_FLIGHTPATH_BEHAVIORS[0].turnsPerEndTurn == 1);
 CHECK(BUDDY_FLIGHTPATH_BEHAVIORS[1].id == "BG20_HERO_283_Buddy_G");
 CHECK(BUDDY_FLIGHTPATH_BEHAVIORS[1].turnsPerEndTurn == 2);
}

TEST_CASE("[Buddy] - Monstrosity death attack behavior is normal/golden") {
 CHECK(BUDDY_DEATH_ATTACK_BEHAVIORS.size() == 2);
 CHECK(BUDDY_DEATH_ATTACK_BEHAVIORS[0].id == "BG20_HERO_282_Buddy");
 CHECK(BUDDY_DEATH_ATTACK_BEHAVIORS[0].attackMultiplier == 1);
 CHECK(BUDDY_DEATH_ATTACK_BEHAVIORS[1].id == "BG20_HERO_282_Buddy_G");
 CHECK(BUDDY_DEATH_ATTACK_BEHAVIORS[1].attackMultiplier == 2);
}

TEST_CASE("[Buddy] - Nightmare Ectoplasm Devour targets are normal/golden") {
 CHECK(BUDDY_DEVOUR_BEHAVIORS.size() == 2);
 CHECK(BUDDY_DEVOUR_BEHAVIORS[0].id == "BG20_HERO_301_Buddy");
 CHECK(BUDDY_DEVOUR_BEHAVIORS[0].extraTargets == 2);
 CHECK(BUDDY_DEVOUR_BEHAVIORS[1].id == "BG20_HERO_301_Buddy_G");
 CHECK(BUDDY_DEVOUR_BEHAVIORS[1].extraTargets == 4);
}

TEST_CASE("[Buddy] - Lei Flamepaw expands Power of the Storm choices") {
 CHECK(BUDDY_STORM_CHOICE_BEHAVIORS.size() == 2);
 CHECK(BUDDY_STORM_CHOICE_BEHAVIORS[0].id == "BG20_HERO_202_Buddy");
 CHECK(BUDDY_STORM_CHOICE_BEHAVIORS[0].optionCount == 3);
 CHECK(BUDDY_STORM_CHOICE_BEHAVIORS[1].id == "BG20_HERO_202_Buddy_G");
 CHECK(BUDDY_STORM_CHOICE_BEHAVIORS[1].optionCount == 4);
}

TEST_CASE("[Buddy] - Living Nightmare after-buy Tavern stats are normal/golden") {
 CHECK(BUDDY_TAVERN_AFTER_BUY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_TAVERN_AFTER_BUY_BEHAVIORS[0].id == "BG20_HERO_280_Buddy");
 CHECK(BUDDY_TAVERN_AFTER_BUY_BEHAVIORS[0].statBonus == 2);
 CHECK(BUDDY_TAVERN_AFTER_BUY_BEHAVIORS[1].id == "BG20_HERO_280_Buddy_G");
 CHECK(BUDDY_TAVERN_AFTER_BUY_BEHAVIORS[1].statBonus == 4);
}

TEST_CASE("[Buddy] - Frostwolf and Stormpike Avenge behavior") {
 CHECK(BUDDY_AVENGE_BEHAVIORS.size() == 4);
 CHECK(BUDDY_AVENGE_BEHAVIORS[0].id == "BG22_HERO_002_Buddy");
 CHECK(BUDDY_AVENGE_BEHAVIORS[1].attack == 2);
 CHECK(BUDDY_AVENGE_BEHAVIORS[2].id == "BG22_HERO_003_Buddy");
 CHECK(BUDDY_AVENGE_BEHAVIORS[3].health == 2);
 CHECK(BUDDY_AVENGE_BEHAVIORS[1].id == "BG22_HERO_002_Buddy_G");
 CHECK(BUDDY_AVENGE_BEHAVIORS[3].id == "BG22_HERO_003_Buddy_G");
}

TEST_CASE("[Buddy] - Warden Thelwater opponent Buddy copy behavior") {
 CHECK(BUDDY_OPPONENT_COPY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_OPPONENT_COPY_BEHAVIORS[0].id == "BG21_HERO_010_Buddy");
 CHECK(BUDDY_OPPONENT_COPY_BEHAVIORS[0].copies == 1);
 CHECK(BUDDY_OPPONENT_COPY_BEHAVIORS[1].id == "BG21_HERO_010_Buddy_G");
 CHECK(BUDDY_OPPONENT_COPY_BEHAVIORS[1].copies == 2);
}

TEST_CASE("[Buddy] - SI:7 Scout after-buy stats are normal/golden") {
 CHECK(BUDDY_AFTER_BUY_STATS_BEHAVIORS.size() == 2);
 CHECK(BUDDY_AFTER_BUY_STATS_BEHAVIORS[0].id == "TB_BaconShop_HERO_01_Buddy");
 CHECK(BUDDY_AFTER_BUY_STATS_BEHAVIORS[0].dbfID == 77479);
 CHECK(BUDDY_AFTER_BUY_STATS_BEHAVIORS[0].statBonus == 2);
 CHECK(BUDDY_AFTER_BUY_STATS_BEHAVIORS[1].id == "TB_BaconShop_HERO_01_Buddy_G");
 CHECK(BUDDY_AFTER_BUY_STATS_BEHAVIORS[1].dbfID == 77538);
 CHECK(BUDDY_AFTER_BUY_STATS_BEHAVIORS[1].statBonus == 4);
}

TEST_CASE("[Buddy] - Snack Vendor Tavern tier stats are normal/golden") {
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS.size() == 2);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[0].id == "TB_BaconShop_HERO_16_Buddy");
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[0].dbfID == 77774);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[0].tavernTier == 3);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[0].attack == 1);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[0].health == 2);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[1].id == "TB_BaconShop_HERO_16_Buddy_G");
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[1].dbfID == 77775);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[1].tavernTier == 3);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[1].attack == 2);
 CHECK(BUDDY_TAVERN_TIER_STATS_BEHAVIORS[1].health == 4);
}

TEST_CASE("[Buddy] - Thawed Champion frozen Tavern copies are normal/golden") {
 CHECK(BUDDY_FROZEN_TAVERN_COPY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_FROZEN_TAVERN_COPY_BEHAVIORS[0].id == "TB_BaconShop_HERO_27_Buddy");
 CHECK(BUDDY_FROZEN_TAVERN_COPY_BEHAVIORS[0].dbfID == 77724);
 CHECK(BUDDY_FROZEN_TAVERN_COPY_BEHAVIORS[0].copies == 1);
 CHECK(BUDDY_FROZEN_TAVERN_COPY_BEHAVIORS[1].id == "TB_BaconShop_HERO_27_Buddy_G");
 CHECK(BUDDY_FROZEN_TAVERN_COPY_BEHAVIORS[1].dbfID == 77725);
 CHECK(BUDDY_FROZEN_TAVERN_COPY_BEHAVIORS[1].copies == 2);
}

TEST_CASE("[Buddy] - Evergreen Botani Tavern-tier hand copies are normal/golden") {
 CHECK(BUDDY_TAVERN_TIER_HAND_BEHAVIORS.size() == 2);
 CHECK(BUDDY_TAVERN_TIER_HAND_BEHAVIORS[0].id == "TB_BaconShop_HERO_74_Buddy");
 CHECK(BUDDY_TAVERN_TIER_HAND_BEHAVIORS[0].dbfID == 77493);
 CHECK(BUDDY_TAVERN_TIER_HAND_BEHAVIORS[0].copies == 1);
 CHECK(BUDDY_TAVERN_TIER_HAND_BEHAVIORS[1].id == "TB_BaconShop_HERO_74_Buddy_G");
 CHECK(BUDDY_TAVERN_TIER_HAND_BEHAVIORS[1].dbfID == 77541);
 CHECK(BUDDY_TAVERN_TIER_HAND_BEHAVIORS[1].copies == 2);
}

TEST_CASE("[Buddy] - Lantern Tender friendly Tavern-tier buff is normal/golden") {
 CHECK(BUDDY_FRIENDLY_TIER_BUFF_BEHAVIORS.size() == 2);
 CHECK(BUDDY_FRIENDLY_TIER_BUFF_BEHAVIORS[0].id == "TB_BaconShop_HERO_75_Buddy");
 CHECK(BUDDY_FRIENDLY_TIER_BUFF_BEHAVIORS[0].dbfID == 77823);
 CHECK(BUDDY_FRIENDLY_TIER_BUFF_BEHAVIORS[0].multiplier == 1);
 CHECK(BUDDY_FRIENDLY_TIER_BUFF_BEHAVIORS[1].id == "TB_BaconShop_HERO_75_Buddy_G");
 CHECK(BUDDY_FRIENDLY_TIER_BUFF_BEHAVIORS[1].dbfID == 77824);
 CHECK(BUDDY_FRIENDLY_TIER_BUFF_BEHAVIORS[1].multiplier == 2);
}

TEST_CASE("[Buddy] - Dagwik Stickytoe golden minion buff is normal/golden") {
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS.size() == 2);
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[0].id == "TB_BaconShop_HERO_64_Buddy");
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[0].dbfID == 77472);
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[0].attack == 5);
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[0].health == 5);
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[1].id == "TB_BaconShop_HERO_64_Buddy_G");
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[1].dbfID == 77535);
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[1].attack == 10);
 CHECK(BUDDY_GOLDEN_FRIENDLY_BUFF_BEHAVIORS[1].health == 10);
}

TEST_CASE("[Buddy] - Piloted Whirl-O-Tron deathrattle copy is normal/golden") {
 CHECK(BUDDY_DEATHRATTLE_COPY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_DEATHRATTLE_COPY_BEHAVIORS[0].id == "BG21_HERO_030_Buddy");
 CHECK(BUDDY_DEATHRATTLE_COPY_BEHAVIORS[0].dbfID == 77874);
 CHECK(BUDDY_DEATHRATTLE_COPY_BEHAVIORS[0].copies == 1);
 CHECK(BUDDY_DEATHRATTLE_COPY_BEHAVIORS[1].id == "BG21_HERO_030_Buddy_G");
 CHECK(BUDDY_DEATHRATTLE_COPY_BEHAVIORS[1].dbfID == 77875);
 CHECK(BUDDY_DEATHRATTLE_COPY_BEHAVIORS[1].copies == 2);
}

TEST_CASE("[Buddy] - Varden Aquarrior refresh highest copy is normal/golden") {
 CHECK(BUDDY_REFRESH_HIGHEST_COPY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_REFRESH_HIGHEST_COPY_BEHAVIORS[0].id == "BG22_HERO_004_Buddy");
 CHECK(BUDDY_REFRESH_HIGHEST_COPY_BEHAVIORS[0].dbfID == 77888);
 CHECK(BUDDY_REFRESH_HIGHEST_COPY_BEHAVIORS[0].statMultiplier == 1);
 CHECK(BUDDY_REFRESH_HIGHEST_COPY_BEHAVIORS[1].id == "BG22_HERO_004_Buddy_G");
 CHECK(BUDDY_REFRESH_HIGHEST_COPY_BEHAVIORS[1].dbfID == 77889);
 CHECK(BUDDY_REFRESH_HIGHEST_COPY_BEHAVIORS[1].statMultiplier == 2);
}

TEST_CASE("[Buddy] - Bilgewater Mogul gold-spent Battlecry is normal/golden") {
 CHECK(BUDDY_GOLD_SPENT_BATTLECRY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_GOLD_SPENT_BATTLECRY_BEHAVIORS[0].id == "TB_BaconShop_HERO_10_Buddy");
 CHECK(BUDDY_GOLD_SPENT_BATTLECRY_BEHAVIORS[0].dbfID == 77847);
 CHECK(BUDDY_GOLD_SPENT_BATTLECRY_BEHAVIORS[0].multiplier == 1);
 CHECK(BUDDY_GOLD_SPENT_BATTLECRY_BEHAVIORS[1].id == "TB_BaconShop_HERO_10_Buddy_G");
 CHECK(BUDDY_GOLD_SPENT_BATTLECRY_BEHAVIORS[1].dbfID == 77848);
 CHECK(BUDDY_GOLD_SPENT_BATTLECRY_BEHAVIORS[1].multiplier == 2);
}
TEST_CASE("[Buddy] - Baby Kodo tier refresh Battlecry is normal/golden") {
 CHECK(BUDDY_TIER_REFRESH_BATTLECRY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_TIER_REFRESH_BATTLECRY_BEHAVIORS[0].id == "BG20_HERO_242_Buddy");
 CHECK(BUDDY_TIER_REFRESH_BATTLECRY_BEHAVIORS[0].dbfID == 77790);
 CHECK(BUDDY_TIER_REFRESH_BATTLECRY_BEHAVIORS[0].copies == 1);
 CHECK(BUDDY_TIER_REFRESH_BATTLECRY_BEHAVIORS[1].dbfID == 77791);
 CHECK(BUDDY_TIER_REFRESH_BATTLECRY_BEHAVIORS[1].id == "BG20_HERO_242_Buddy_G");
 CHECK(BUDDY_TIER_REFRESH_BATTLECRY_BEHAVIORS[1].copies == 2);
}
TEST_CASE("[Buddy] - Crabby hero-power damage dispatch is normal/golden") {
 CHECK(BUDDY_HERO_POWER_DAMAGE_BEHAVIORS.size() == 2);
 CHECK(BUDDY_HERO_POWER_DAMAGE_BEHAVIORS[0].id == "BG22_HERO_000_Buddy");
 CHECK(BUDDY_HERO_POWER_DAMAGE_BEHAVIORS[0].dbfID == 77880);
 CHECK(BUDDY_HERO_POWER_DAMAGE_BEHAVIORS[0].multiplier == 1);
 CHECK(BUDDY_HERO_POWER_DAMAGE_BEHAVIORS[1].dbfID == 77881);
 CHECK(BUDDY_HERO_POWER_DAMAGE_BEHAVIORS[1].id == "BG22_HERO_000_Buddy_G");
 CHECK(BUDDY_HERO_POWER_DAMAGE_BEHAVIORS[1].multiplier == 2);
}
TEST_CASE("[Buddy] - Many Whelps summon growth is normal/golden") {
 CHECK(BUDDY_WHELP_SUMMON_BEHAVIORS.size() == 2);
 CHECK(BUDDY_WHELP_SUMMON_BEHAVIORS[0].id == "BG22_HERO_305_Buddy");
 CHECK(BUDDY_WHELP_SUMMON_BEHAVIORS[0].dbfID == 77890);
 CHECK(BUDDY_WHELP_SUMMON_BEHAVIORS[0].attack == 2);
 CHECK(BUDDY_WHELP_SUMMON_BEHAVIORS[1].id == "BG22_HERO_305_Buddy_G");
 CHECK(BUDDY_WHELP_SUMMON_BEHAVIORS[1].dbfID == 77891);
 CHECK(BUDDY_WHELP_SUMMON_BEHAVIORS[1].attack == 4);
}
TEST_CASE("[Buddy] - Submersible Chef tier hand Battlecry is normal/golden") {
 CHECK(BUDDY_TIER_HAND_BATTLECRY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_TIER_HAND_BATTLECRY_BEHAVIORS[0].id == "BG22_HERO_201_Buddy");
 CHECK(BUDDY_TIER_HAND_BATTLECRY_BEHAVIORS[0].dbfID == 82604);
 CHECK(BUDDY_TIER_HAND_BATTLECRY_BEHAVIORS[0].copies == 1);
 CHECK(BUDDY_TIER_HAND_BATTLECRY_BEHAVIORS[1].id == "BG22_HERO_201_Buddy_G");
 CHECK(BUDDY_TIER_HAND_BATTLECRY_BEHAVIORS[1].dbfID == 82606);
 CHECK(BUDDY_TIER_HAND_BATTLECRY_BEHAVIORS[1].copies == 2);
}
TEST_CASE("[Buddy] - Magnus Manastorm buy-tier Tavern copies are normal/golden") {
 CHECK(BUDDY_BUY_TIER_TAVERN_BEHAVIORS.size() == 2);
 CHECK(BUDDY_BUY_TIER_TAVERN_BEHAVIORS[0].id == "TB_BaconShop_HERO_49_Buddy");
 CHECK(BUDDY_BUY_TIER_TAVERN_BEHAVIORS[0].dbfID == 77803);
 CHECK(BUDDY_BUY_TIER_TAVERN_BEHAVIORS[0].copies == 1);
 CHECK(BUDDY_BUY_TIER_TAVERN_BEHAVIORS[1].id == "TB_BaconShop_HERO_49_Buddy_G");
 CHECK(BUDDY_BUY_TIER_TAVERN_BEHAVIORS[1].dbfID == 77804);
 CHECK(BUDDY_BUY_TIER_TAVERN_BEHAVIORS[1].copies == 2);
}

TEST_CASE("[Buddy] - Tuskarr Raider pirates-played Battlecry is normal/golden") {
 CHECK(BUDDY_PIRATES_PLAYED_BATTLECRY_BEHAVIORS.size() == 2);
 CHECK(BUDDY_PIRATES_PLAYED_BATTLECRY_BEHAVIORS[0].id == "TB_BaconShop_HERO_18_Buddy");
 CHECK(BUDDY_PIRATES_PLAYED_BATTLECRY_BEHAVIORS[0].dbfID == 77815);
 CHECK(BUDDY_PIRATES_PLAYED_BATTLECRY_BEHAVIORS[0].multiplier == 1);
 CHECK(BUDDY_PIRATES_PLAYED_BATTLECRY_BEHAVIORS[1].id == "TB_BaconShop_HERO_18_Buddy_G");
 CHECK(BUDDY_PIRATES_PLAYED_BATTLECRY_BEHAVIORS[1].dbfID == 77816);
 CHECK(BUDDY_PIRATES_PLAYED_BATTLECRY_BEHAVIORS[1].multiplier == 2);
}
